# Generated by Django 5.2.4 on 2025-08-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_sale_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
