# Generated by Django 5.2.4 on 2025-08-09 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_sale_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale_price',
        ),
    ]
